# Generated by Django 6.1.1 on 2026-09-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_OTP', to='accounts.user'),
        ),
    ]
